name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # ensure the action can push back (uses GITHUB_TOKEN)
          persist-credentials: true
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - name: Install dependencies (npm)
        run: npm install

      - name: Build (client + server)
        # This runs your local equivalent: npm run build -> builds client and server
        run: npm run build

      - name: Prepare SPA fallback
        # GitHub Pages serves 404.html for unknown routes; copy index.html so client-side routing works
        run: cp ./dist/spa/index.html ./dist/spa/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/spa       
          publish_branch: gh-pages   
          keep_history: true
          cname: freepalestine.sh
